### ISSUE TITLE
Acronyms used as names in citations

### ISSUE THREAD

**Issue by generalist** [MartinPaulEve/meTypeset#108]
The suggested approach [discussed here](https://www.martineve.com/2017/02/10/on-automatically-detecting-parenthetical-citations/) (and implemented [here](https://github.com/MartinPaulEve/meTypeset/commit/b9126e4df918b915d5ca557448b2a12422746a18)) identifies authors using:

> - A set of words that are all capitalised on the first letter only, followed by a series of other words, numbers, or special characters [; or]
> - A set of numbers following an optional p. or P.

One edge case that I've seen (and indeed done myself) is that some citations will use an acronym as an author name, particularly with large collaborations or corporate authors - eg Google Scholar throws up ~500 papers using "IPCC 2015", most of which seem to be using it as an in-text parenthetical citation to the 2015 IPCC report.

Perhaps a suitable additional approach would be to use a rule like:

> - A word that contains multiple capitals, then a series of other words, numbers, or special characters, then the string ending (with or without punctuation) by a number that resembles a year [four digits?]

This would catch most of the acronyms (a multiple-capital rather than all-capital rule would eg allow for some of the odd capitalisations in Russian-derived acronyms) while only identifying ones that fit the basic format of "name, year" and are thus relatively unlikely to be false positives.

**Comment by MartinPaulEve** [comment]
Ah ha. Thanks so much for this.

So, I'm just writing a test case that catches the last three of these:

A test (IPCC).

Another test (IPCC 2015).

A final test (IPCC Report 2015)

A test (2015 IPCC Report)

Will then see what I can create to catch those with the regex.

**Comment by MartinPaulEve** [comment]
Expanding the scope slightly to include all but the first of these:

A test (IPCC).
A test (IPCC, p. 54).
Another test (IPCC 2015).
A final test (IPCC Report 2015)
A final test (IPCC Report 2015, 95)
A test (2015 IPCC Report, p. 54)

**Comment by MartinPaulEve** [comment]
Pushed in 6456f312606170367e391f543f032ed656eae690

**Comment by MartinPaulEve** [comment]
Expanding regex to (?:\((?P<text>((?:[A-Z]{1}[a-z\s,\.\d\;&]+)*|(?:(?:\d{4}\s)?[A-Z]+[\s\,](?:[A-Z]{1}[a-z\s,\.\d\;&]*)?(?:\d{4})?(?:[a-z\s,\.\d\;&]+)*)|(?:p?P?\.?\s?\d+))|.+\<ref\s.+)\)) seems to catch all test cases and doesn't break existing handling.

**Comment by MartinPaulEve** [comment]
I think this is now fixed. If there are other edge cases, please do give examples and I'll add them!
