### ISSUE TITLE
Update DOCTYPE declaration to reflect JATS?

### ISSUE THREAD

**Issue by axfelix** [MartinPaulEve/meTypeset#113]
Not sure if this is intentional, but meTypeset still generates documents with an NLM 3 DOCTYPE declaration, even though the NLM 3 elements used are, in my experience, a 100% valid subset of JATS 1.0.

Any desire to update this on the meTypeset side? Right now we're just replacing the DOCTYPE in OTS once we've passed meTypeset's output through our other parsers...

**Comment by MartinPaulEve** [comment]
Note: if you don't run the metadata module, you may still get an NLM doctype. Please let me know if this is still happening for you (and let me know which params you are passing).
