### ISSUE TITLE
disp-quote elements generated inside of td where they aren't allowed

### ISSUE THREAD

**Issue by axfelix** [MartinPaulEve/meTypeset#117]
See example:

[test.docx](https://github.com/MartinPaulEve/meTypeset/files/1768528/test.docx)

**Comment by axfelix** [comment]
This also happens inside `<fn>` elements, FYI -- can provide an example there too. meTypeset likes disp-quote a lot :)

**Comment by axfelix** [comment]
Got some more disp-quote weirdness here; this document (not yet reduced to a small test case; I can do that if you want) produces the structure `<disp-quote><p><p>` which is obviously not OK.
[dispquote-p-p.docx](https://github.com/MartinPaulEve/meTypeset/files/1768636/dispquote-p-p.docx)

**Comment by axfelix** [comment]
[disp-quote-ahoy.docx](https://github.com/MartinPaulEve/meTypeset/files/1772633/disp-quote-ahoy.docx)

One more example of a document that produces too many `disp-quote`s...

**Comment by axfelix** [comment]
One more for good measure.

[3 ijsrm.zip](https://github.com/MartinPaulEve/meTypeset/files/2007004/3.ijsrm.zip)

This is by some margin the biggest issue we're still having with meTypeset's parsing, and the one I'm least enthusiastic to fix -- a lot of disp-quote generated where it's not allowed.

**Comment by MartinPaulEve** [comment]
Hi Alex,

I'm happy to have a go at fixing this, but could you provide me, please, with the minimal documents to generate bad disp-quote tags? Then I can easily write a test and start to fix.

M

**Comment by axfelix** [comment]
Hi Martin,

The test.docx in the very first comment is already pretty minimal -- I'd forgotten I already pared that one down :)

**Comment by MartinPaulEve** [comment]
Please do reopen if you find other cases.
