### ISSUE TITLE
python meTypeset.py finished with an "ImportError: No module named editdistance" error

### ISSUE THREAD

**Issue by juanCure** [MartinPaulEve/meTypeset#119]
Hi I have installed meTypeset through the INSTALL.md instructions, when I try to run the simple command:

`python meTypeset.py`

I have got the following messages of error:

```
Traceback (most recent call last):
  File "meTypeset.py", line 57, in <module>
    from captionclassifier import CaptionClassifier
  File "/usr/local/meTypeset/bin/captionclassifier.py", line 23, in <module>
    import editdistance
ImportError: No module named editdistance
```

Someone has idea of how resolve this issue?

These are my the versions of the installed dependencies for meTypeset:
**Java "1.8.0_161"
Python 2.7.12
and LibreOffice 5.1.6.2**

**Comment by MartinPaulEve** [comment]
Hi,

First, follow all instructions in this file:
https://github.com/MartinPaulEve/meTypeset/blob/master/INSTALL.md

Then you need to use pip to install other dependencies. Apologies - these
are not well documented at present.

In this case you need to do pip install editdistance

Martin

**Comment by juanCure** [comment]
Thanks a lot for your soon response. 

I use meTypeset for convert some Microsoft Word files  to JATS/XML files. I have installed editdistance through pip and meTypeset works correctly.
