### ISSUE TITLE
meTypeset Installation

### ISSUE THREAD

**Issue by smoriarti** [MartinPaulEve/meTypeset#140]
Tried to install on Ubuntu 18.04.2 LTS.
When run
git clone https://github.com/MartinPaulEve/meTypeset.git

I got: 
E: can not find package clone
E: can not find package https://github.com/MartinPaulEve
E: cannot find any package with templates «https://github.com/MartinPaulEve»
E: cannot find any package with regular expression «https://github.com/MartinPaulEve»

What I did wrong?

**Comment by MartinPaulEve** [comment]
Hi,

You do not have a working installation of git, which you need to clone the repo.

I should warn that if you are not familiar with basic Linux commands, git, installing prerequisites etc. then meTypeset is probably not suitable for your use.
