### ISSUE TITLE
pybot doesn't seem to like external unoconv calls

### ISSUE THREAD

**Issue by axfelix** [MartinPaulEve/meTypeset#79]
Looks like documents containing wmf/emf images that would normally make a call out to unoconv hang meTypeset until the specified timeout (currently 30s) when run by pybot. Works fine when meTypeset called directly with the same args. Can't say I'm surprised given how relatively weird the unoconv/LibreOffice kit is, but trying to track this down.

**Comment by MartinPaulEve** [comment]
Strange. Could this be an environment problem?

On 07/07/15 18:21, axfelix wrote:
> Looks like documents containing wmf/emf images that would normally make
> a call out to unoconv hang meTypeset until the specified timeout
> (currently 30s) when run by pybot. Works fine when meTypeset called
> directly with the same args. Can't say I'm surprised given how
> relatively weird the unoconv/LibreOffice kit is, but trying to track
> this down.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MartinPaulEve/meTypeset/issues/79>.
>

-- 
Dr. Martin Paul Eve
Senior Lecturer in Literature, Technology and Publishing
Birkbeck, University of London

T: 02030 738 420
E: martin.eve@bbk.ac.uk
W: https://www.martineve.com
R: 416, 43 Gordon Square, London, WC1H 0PD

Pynchon and Philosophy: http://meve.io/pynchonphilo
Open Access and the Humanities: http://meve.io/oahums

Director, Birkbeck Centre for Technology and Publishing
Founder, Open Library of the Humanities (https://www.openlibhums.org)
Chief Editor, Orbit: Writing Around Pynchon (https://www.pynchon.net)
Senior Online Editor, Alluvium, (http://www.alluvium-journal.org)

**Comment by axfelix** [comment]
Probably.

**Comment by axfelix** [comment]
Actually, wait a second -- nevermind. False alarm. Closing :)
