### ISSUE TITLE
Sizeclassifier verification

### ISSUE THREAD

**Issue by withanage** [MartinPaulEve/meTypeset#88]
Sometimes it is very useful to run the typestter without stopping although the chapters are disordered after size classification. It would help to  identify various problems, that would occur due the false formatting of headers.
Exactly here:
https://github.com/MartinPaulEve/meTypeset/blob/master/bin/sizeclassifier.py#L329

One option would be to add a parameter  to main program to  run the program without stopping.
The other option (what I prefer ) is to   return a debug message saying which element  generates the disordering.  I did not find any way to return that element other than outputting the whole stack.
@MartinPaulEve  is there any way to do that?
If not, I would implement the first option, would you think , that is  general enough to be included in the metypeset main fork.

**Comment by MartinPaulEve** [comment]
Hi Dulip,

I'm at a conference all this week but just to ask... Can this not be
controlled by lowering the aggression level of meTypeset?

Best wishes,

Martin

**Comment by withanage** [comment]
Hi Martin, 
thanks for answering in the middle of the conference.
I reduced the aggression to 4 and that solved the issued. Thanks again!
Best,
Dulip
